databacker/mysql-backup

Dockerfile
Tags the Alpine image for current version as the `latest` tag can and will change soon. It is better to have a deterministic build and test upgrades to later versions.
=> Tag the Alpine image so it doesn't change from under us

Dockerfile, README.md, entrypoint
resolves deitch/mysql-backup#2
Could use some tests. I can't see a nice way to fit s3 tests into the current `test.sh`. If someone is a better bash wizard than I wants to pick that up I'd be quite pleased.
Failing that, I'll write a separate script to test s3 tomorrow.
=> Add S3 support

Dockerfile
Updates:
* Alpine to 3.5
* python to python3
* awscli to 1.11.82 (or whatever is latest at time of build)
=> Update Dockerfile to python3 and get latest awscli

README.md, entrypoint
=> Provide option for selecting which databases to restore

entrypoint
=> Enable spaces in username and password

README.md, entrypoint
=> Add support for SMB_USER and SMB_PASS

Makefile
=> Push latest

README.md, entrypoint, test/test.sh
=> Enable DBSERVER and DBPORT config; remove recommendation to use links

README.md, entrypoint, scripts.d/post-backup/rename_backup.sh.example
Added two new variables:
- DESTDIR: To export the destination directory so for example you can copy a new tarball including some other files along with the sql dump.
- DB_DUMP_DEBUG: To enable debug mode in post-backup scripts.
=> Export two new variables: DESTDIR and DB_DUMP_DEBUG

README.md, entrypoint, test/test.sh
Ok, this is for the rest of pre/post processing operations:
- Pre-backup
- Pre-restore
- Post-restore
I'm already working on a restore script to test the post-backup results.
=> Post restore scripts

Dockerfile, entrypoint, functions.sh
Hi,
This one is more of cosmetic kind, I think moving the uri_parser to a separate file makes the code more clear and readable.
WDYT ?
=> Move functions in entrypoint to separate file to make code more readable

entrypoint
otherwise, the job will try to re-run if you set the `restartPolicy:OnFailure`
thanks so much for this project! <3
=> when using kubernetes cronjob you need exit 0 if success

README.md
=> Document non-root impact

README.md, entrypoint, functions.sh
=> Add options to select compression

functions.sh
This should make it easier to work with the compressed tar archive directly.
=> Add timestamp to name of files in tar archive

functions.sh
=> Fix misused var in per-database file naming

entrypoint
=> Use tar options correctly

.travis.yml, Dockerfile, Makefile, README.md, entrypoint, functions.sh, test/Dockerfile_smb, test/_functions.sh, test/test_cron.sh, test/test_dump.sh, test/test_source_target.sh
=> Enable usage of cron format

entrypoint, functions.sh, test/test_cron.sh
Also, simplify usage of date/time in `wait_for_cron`
=> Ensure cron is at least 60 seconds since last invocation

functions.sh, test/test_cron.sh
=> Handle current minute correctly and add test for it

functions.sh
=> use correct dowDiff to calculate dow diff for cron

Dockerfile
=> Ensure minimum mariadb-client version for --all-databases bug

.travis.yml, entrypoint, functions.sh
=> Proper exit codes for failures

README.md, entrypoint, functions.sh
=> add AWS_CLI_OPTS option

.github/workflows/main.yml
Forgot to add tags as conditions for actions invocation.
=> trigger tags

CONTRIBUTORS.md, README.md, examples/docker-compose.yaml, functions.sh
Signed-off-by: Anish Dhanka <anish.mourya5@gmail.com>
=> ionice & nice added to mysqldump to fix high cpu resource issue

README.md, entrypoint, functions.sh
=> Add feature to use custom tmp directory

functions.sh, test/ctr/cron_test.sh
Fixes #171 replaces #172 
Includes the test case from #172 but also the fix for #171. 
With thanks to @flipkick for the test.
=> Fix cron calculations

README.md, examples/docker-compose.yaml
=> updated README and example for docker-compose with multiple targets

functions.sh, test/ctr/cron_test.sh
=> fix month rollover

Dockerfile, test/Dockerfile_smb
Fixes #107 
Fixes #200 
Supersedes #108
=> fix samba private dir perms

functions.sh
See https://github.com/databacker/mysql-backup/issues/205
=> ISSUE-205: fix $AWS_CLI_S3_CP_OPTS in backup process

.github/workflows/ci.yaml, .github/workflows/deploy.yaml, .github/workflows/release.yaml, Makefile
=> multiarch build, both Makefile and GHActions

Dockerfile, test/Dockerfile_smb
Hoping it doesn't break too many things...
=> alpine:3.17

.github/workflows/release.yaml
=> cut release on tag

cmd/dump.go, cmd/dump_test.go, cmd/restore.go, cmd/root.go, cmd/testdata/config.yml, pkg/config/type.go
In addition, add the missing CLI flag, and unify how empty slices are handled in cmd options
=> properly input config file

pkg/database/mysql/dump.go
=> do not dump generated columns

sample-configs/local.yaml, sample-configs/remote.yaml, sample-configs/telemetry-only.yaml
No changes, just renamed for simplicity and added comments.
Note that these configs still are subject to change.
=> udpate sample configs

cmd/root.go, docs/configuration.md
See #287. Does not fix all of the issues raised, but most.
=> update doc errors; remove unused parameters

go.mod, go.sum, pkg/compression/bzip2.go, pkg/compression/compressor.go, pkg/compression/gzip.go, pkg/core/dump.go
=> add bzip2 support

entrypoint
=> restore nice support

cmd/dump_test.go, cmd/restore_test.go, cmd/root.go
Fixes #297 ; includes tests, of course
=> use default port when it is explicitly set, or it is not set in config file

pkg/database/mysql/dump.go
Fixes #304 (hopefully). Instead of hard-coding charset and collation for a database, queries it.
=> get database charset and collation from query rather than hard-code

go.mod, go.sum
=> update deps for security reasons

cmd/dump.go, cmd/dump_test.go
Fixes #323 
Also adds proper tests for CLI processing of flags for pre-backup and post-backup
=> Handle post backup path

README.md, docs/backup.md, docs/configuration.md, docs/scheduling.md
=> update docs to correctly reflect the env var for DB_DUMP_FREQUENCY

.github/workflows/ci.yaml
Sorry, I ignored the pull request 😬😬😬 #356
=> Fix workflow execution error

pkg/core/prune.go, pkg/core/prune_test.go
It was not correctly calculating how many files to prune and which ones.
=> fix prune when based on counting

examples/docker-compose.yaml
=> fix wrong database service reference in example compose.yaml
