README.md, entrypoint
In some instances (e.g. external scheduler, orchestration solutions), it might be desirable to run only once and let a container-external solution do the scheduling.
With this patch, such a behaviour can be achieved by setting ``RUN_ONCE=1`` as a new config option of the container.
=> Add possibility to run once

README.md, entrypoint
Any environment variable that begins `MYSQLDUMP_` will have the first part `MYSQLDUMP_` stripped off, and the rest passed as var options to `mysqldump`.
Updated README as well.
=> Allow generic vars to pass options to mysqldump

README.md, entrypoint, functions.sh, test/test.sh
(Closes #26)
Used the same `file_env` function from mysql image's entrypoint (https://github.com/docker-library/mysql/blob/0590e4efd2b31ec794383f084d419dea9bc752c4/5.7/docker-entrypoint.sh#L25).
=> Enable reading variables from files as well (docker/rancher secrets)

Dockerfile, test/Dockerfile_smb, test/test.sh
Before we (unwisely) used `docker run mysql` in tests, which defaults to the `latest` tag. As of `mysql` version `8.0.4` and above, the default auth mechanism for `mysql` is caching sha2. Our client is based on `alpine:3.7`, whose `mysql-client` package is based on `mariadb`, which does not include that plugin.
Here we limit it.
=> Tie mysql to 5.7 because of auth requirements for 8.0.4+

entrypoint
Fixes #51 
Restores usage of `$DUMPVARS` to `mysqldump`. It was accidentally deleted in the complex merge of #29 .
=> Restore usage of DUMPVARS

Dockerfile
No good reason for it to run as root... and it does make the tests more brittle. This is better.
=> No longer run as root

.travis.yml, Makefile, README.md, entrypoint, test/_functions.sh, test/test.sh, test/test_source_target.sh
Implemented a plugin for overriding the dump file name **before** it gets uploaded to the dump target.
PR for issue: https://github.com/deitch/mysql-backup/issues/52
@deitch I gave some thought to testing this upgrade, but your test script would not complete each time I tried. I kept getting the following error repeated in my shell:
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
Looking at your script, all mysql commands are run within containers, so there should be no requirement for me to have the mysql server installed on my host. Is there a specific way I need to run your test script?
=> implement target name override plugin

README.md, entrypoint, functions.sh, test/_functions.sh, test/test.sh, test/test_source_target.sh
=> Add support for using multiple files, one per schema

README.md, entrypoint, functions.sh
In certain circumstances - e.g. some NFS shares on Windows - if the `DB_DUMP_TARGET` is a `file:///` target, it may have issues copying the file with permissions (`cp -a`). This provides an option to disable it.
Fixes #65
=> Option to override keeping permissions for file: targets

README.md, entrypoint, functions.sh
Makes it easier to pass in multiple and possibly complex options to `mysqldump`.
=> Consolidate all mysqldump opts to a single option

Dockerfile, test/Dockerfile_smb, test/test_dump.sh, test/test_source_target.sh
This **cannot** yet be merged. However, once alpine 3.9 goes GA, it should be ready to go.
=> Alpine 3.9, mariadb 3.0.8 support for caching_sha2 auth, test against mysql 8.0.13

Makefile, test/test_dump.sh, test/test_source_target.sh
Adds labels to all containers and networks created during tests, and uses those labels to remove them in `clean-test` target in Makefile.
Also cleans up conditional Makefile logic for `clean-test`
=> Better make clean target

README.md
I was happy to find that I can use this tool with my DigitalOcean spaces by using the AWS_ENDPOINT_URL but it wasn't documented anywhere so I thought I would help out. 
I haven't tested this with restoration, only backing up but it works great!
=> Document DigitalOcean interopabality options

Dockerfile, README.md, examples/encrypt.sh
Fixes #123 with many thanks to @sascha-schieferdecker
=> Add openssl support and example

.github/workflows/main.yml, Makefile
Several things:
* Clean up Makefile so that the build is always `databack/mysql-backup:build`, and tags and pushes out images based on the passed `TAG` var to Makefile, or default to the git hash
* Add support for pushing out tagged images
=> Add tagged releases and clean up actions

README.md, entrypoint
This adds a new environment variable: `AWS_CLI_S3_CP_OPTS`.
Due to project requirements we required a KMS key per tenant in a shared bucket (in which each tenant has its own object prefix). Since this cannot be achieved using a default configuration in the bucket itself, we added a new variable to this project allowing additional options to be passed to the `cp` subcommand of the AWS CLI.
=> Add aws cli s3 param

README.md, functions.sh
This PR will allow the image to run mysqldump command without `--database` flag, it makes the dump file more flexible as you can import in a database with a different name, as it will create the export file without `USE {databasename};` statement.
=> Create mysqldumps without USE DATABASE statement

entrypoint
Fixes #174 
The following is the current date format:
```sh
date --date="${today}${DB_DUMP_BEGIN}" +"%s"
```
It works fine if `today` is set and `DB_DUMP_BEGIN` is not, leading to something like:
```sh
date --date="20211210" +"%s"
```
However, if `DB_DUMP_BEGIN` is set, you end up with:
```sh
date --date="202112100100" +"%s"
```
which is invalid. You need a `T` between them for it to be valid:
```sh
date --date="20211210T0100" +"%s"
```
=> ensure format is correct

README.md, entrypoint, functions.sh
I recently had the same issues with the "information_schema" database when using mysqldump. Even after reading a lot of pages I could not find a solution to dump the various internal database without any issue. Also from what I understood it also is not useful to do backups of those DBs at all.
Hence I checked the closed #139 (which addresses #138) and stripped away the timezone handling stuff as this is a topic on its own. I also change the spelling corrections you mentioned. Last but not least I did a few tests with the changed code. It seems to work as expected.
So I'm asking to to consider this pull request. If you see any issues or changes needed just let me know. I will try to help as good as I can.
=> Re-submitted PR 139 to exclude databases (but without timezone handling)

README.md, entrypoint
Currently, the docker image has no way to restore a database saved with the option `SINGLE_DATABASE=true`. This pull request makes it possible.
Specify `SINGLE_DATABASE=true` and `DB_NAMES` variable along with `DB_RESTORE_TARGET` to restore a single database to the database named `DB_NAMES`. `DB_NAMES` is expected to contain one database name, not space-separated multiple database names despite its plural variable name.
Implementation of #121.
=> Restore single database

Dockerfile
When running a container using IRSA to manage permissions any aws cli commands failed with an error around /home/appuser not existing
This fix creates the home folder as part of the dockerfile which resolves the issue
=> AWS IRSA Fix

README.md, entrypoint
Use the `DB_NAMES` variable without `SINGLE_DATABASE` to specify one or more databases to restore from a backup archive generated with `DB_DUMP_BY_SCHEMA`.
I am not a bash expert, so feel free to test and review my code. I tested it for simple cases without errors. Also, as I made it, there can be issues when schema names are overlapping.
=> Restore specific schema from archive

pkg/database/mysql/dump.go, test/backup_test.go
This is not technically required to work, but removes the possibility of uncertainty and mismatched columns. It also makes debugging easier, as a nice side benefit.
=> include column names in INSERT statement

README.md
Place commands after docker image
=> Readme: fix docker run commands

pkg/core/timer.go
Per [this comment](https://github.com/databacker/mysql-backup/issues/267#issuecomment-1943722777)
We may add timezone support in the future, but for now we should consistent.
=> use UTC for timer as well to be consistent

cmd/dump.go, cmd/dump_test.go, pkg/core/timer.go
Closes #265 
Changes:
- Make the flags themselves mutually exclusive and remove check in timer.go. This check always failed when using cron, as the begin and frequency options are populated with defaults.
- add else if for timer creation, to prevent overwriting cron delay with `begin +0` delay from default
=> Make once, cron and begin/frequency flags mutually exclusive

README.md, cmd/common_test.go, cmd/dump.go, cmd/dump_test.go, cmd/prune.go, cmd/prune_test.go, cmd/restore.go, cmd/restore_test.go, cmd/root.go, cmd/testdata/config.yml, docs/configuration.md, docs/prune.md, pkg/config/type.go, pkg/core/dump.go, pkg/core/prune.go, pkg/core/prune_test.go, pkg/core/pruneoptions.go, pkg/core/timer.go, pkg/storage/file/file.go, pkg/storage/s3/s3.go, pkg/storage/smb/smb.go, pkg/storage/storage.go, test/backup_test.go
Fixes #274 
Create retention option for `dump`, where it goes through older backups and delete any that are outside the retention window.
This is enabled in 2 scenarios via the `RETENTION` env var / `--retention` flag / `prune.retention` config file option:
* during backups
* with a new `mysql-backup prune` command
A new `docs/prune.md` page has been created, and the option has been added to `docs/configuration.md`
Currently draft as it only includes the docs.
=> enable retention

pkg/core/timer.go, pkg/core/timer_test.go
Closes #267 
- Parsing of start time failed, because regex produces 3 matching groups, not more
=> Fix parsing begin time flag

pkg/core/timer.go
Closes #278 
Cron delay is always calculated relative to startup time, so its correct on the first run and wrong afterward.
I have no good way of adding a test for this, without restructuring it or injecting a dummy sleep function.
=> fix: Cron consecutive runs

pkg/database/connection.go, pkg/database/mysql/date.go, pkg/database/mysql/dump.go, test/backup_test.go
Based on #273 but extends it with full handling of dates.
With many thanks and full credit to @FluffyEscargot for starting it and giving most of the solution.
=> fix datetime parsing

README.md, docs/configuration.md, docs/database_address.md, pkg/database/connection.go, pkg/database/schemas.go
As discussed in  #285
This changes the semantics of `--server` (or the env var, etc) to `--server <IP/FQDN | /path/to/socket>`
=> Support connecting with a unix domain socket

cmd/root.go, pkg/storage/credentials/creds.go, pkg/storage/parse.go, pkg/storage/s3/s3.go, test/backup_test.go
It was using the endpoint, but ignoring credentials. It still worked using env vars, but not with CLI overrides.
=> fix s3 session creation

pkg/storage/s3/s3.go
Fixes #296 
It was _always_ setting an endpoint resolver, even if that endpoint was `""`. That would break it. Do so only if the endpoint override is _not_ `""`.
=> set s3 endpoint resolver only if it is non-blank

pkg/database/mysql/dump.go, pkg/database/mysql/table.go, pkg/database/mysql/view.go, test/backup_test.go
Fixes #275 
Because we called `SHOW TABLES`, we mixed in base tables and views. Normally that is fine, their handling is _almost_ identical, but the `SHOW CREATE TABLE` for views also returns 2 more columns.
This fix creates a `Table interface` and then has 2 implementations: `baseTable` and `view`. `view` pretty much just embeds `baseTable`, but overrides `CreateSQL()`, where it handles the 4 columns correctly.
Also added a test in `backup_test.go` wherein it creates a view. I expect the initial integration test to fail, but that is a test issue.
=> handle views separately from tables

cmd/dump_test.go, cmd/prune_test.go, cmd/restore_test.go
The output was making it hard to see the actual error messages for failed tests, and didn't add anything.
=> when in tests, send cobra help and errors to discard

pkg/database/mysql/table.go
Fixes #313 
The `unsigned bigint` defaults to being `*uint64`, which is correct (other than the fact that it is not nullable). This enables the code to read it properly.
=> handle basic types as well

docs/configuration.md, docs/scheduling.md, test/test_restore.sh
The env vars for all dump configuration have the following characteristics:
* start with `DB_DUMP_`
* use the name of the CLI flag after the prefix, converted to upper-case, and with `-` switched to `_`
So `--begin` becomes `DB_DUMP_BEGIN`, etc.
There is one exception to this, `--once` which uses the env var `RUN_ONCE` rather than `DB_DUMP_ONCE`. This causes a lot of headaches, and libraries that do not handle it correctly, etc.
Since 1.0.0 is not yet GA, we are just switching the env var.
=> switch once env var to fit with others

pkg/core/prune.go, pkg/core/prune_test.go
=> Fix pruning to work with safechars

pkg/database/mysql/table.go, test/backup_test.go
json is not recognize by default as a type in the mysql package, so we need to give it its own type recognition.
Compared the results to `mysqldump` and the values are consistent.
Also added to the integration test.
Fixes #322
=> handle json field as its own type

pkg/core/dump.go, pkg/core/scripts.go
These were used in the old bash-based version. In the newer version (from `1.0.0-rc*` onwards):
* they were not documented anywhere
* they depended on a hard-coded path to `/scripts.d/`, which only made sense in a container context
* `source.sh` is unneeded as you can use post-backup scripts, which include an example of adding data to the backup file
* `target.sh` is unneeded, as you have the option `--filename-pattern`
=> remove unnecessary and undocumented source.sh and target.sh

.github/workflows/release.yaml
We were using the action `crazy-max/xgo` to build the artifacts for release. For some reason, they were not showing up in `dist/`, and thus the release was not finding them. Since #337 has a simple `make build-all`, we can use that instead.
=> switch release builds from xgo to simple make build-all

cmd/common_test.go, cmd/dump.go, cmd/dump_test.go, cmd/root.go, cmd/testdata/pattern.yml, pkg/core/const.go, pkg/core/dump.go, pkg/core/dumpoptions.go, pkg/core/dumpresults.go, pkg/storage/file/file.go, pkg/storage/s3/s3.go, pkg/storage/smb/smb.go, pkg/storage/storage.go, test/backup_test.go
It was not being reference. This should fix it.
=> fix filename-pattern

cmd/root.go, docs/configuration.md
=> make DB_DEBUG env var work

.github/workflows/ci.yaml
If we did it with `filter-path`, PR status got stuck waiting. This adds it to a particular job. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
=> next attempt for docs-only CI

Dockerfile
- alpine 3.20
- golang 1.21.13
- optimize image build, 32.6MB vs. 34.4MB of the actual master tag. It's a full floppy! :)
=> Alpine 3.20 based Docker image

pkg/storage/s3/s3.go
When passing the target key to S3 via the library as:
```go
_, err = uploader.Upload(context.TODO(), &s3.PutObjectInput{
Bucket: aws.String(bucket),
Key:    aws.String(path.Join(key, target)),
Body:   f,
})
```
It expects the `Key` to start _without_ a slash, as it always adds one. This change ensures that it always is clean.
=> ensure that S3 Push does not double-slash at beginning

.github/workflows/ci.yaml, .github/workflows/deploy.yaml, .github/workflows/release.yaml
Hello,
I have seen some warnings about versions into Actions logs, and then I have upgraded all versions of GitHub Actions. Unfortunately, I cannot test it on my fork, so that is the reason for the draft PR (I hope that will allow running CI workflows).
Best,
Jonathan Dreyer
=> Upgrade GitHub Actions version for CI, Release & Deploy

pkg/core/prune.go
This was causing weird log messages, like:
```
DEBU[0000] pruning 0 files from target &{{s3  %!s(*url.Userinfo=<nil>) *********-backup-mumbai /mysql/dumps-frequent  %!s(bool=false) %!s(bool=false)   } %!s(bool=false)    }  run=7f4831e8-7247-4674-8bd2-4ccaefa848a
```
=> when reporting logging messages for prune targets, correctly report the target URL

docs/configuration.md
reference: https://github.com/databacker/api/blob/main/go/api/schemas.go#L244
Yaml keys are case-sensitive. this was too tough to debug... I almost gave up.
=> fix configuration.md type

pkg/core/dump.go
It was reporting `provided-schemas` as `true` when `len(dbnames)==0`, which is the opposite. Schemas were provided when the len != 0.
=> was reporting provided-schemas telemetry as false when true

README.md, docs/backup.md, pkg/database/dump.go
=> update docs and comments to remove last vestiges of DB_NAMES

cmd/dump.go, docs/configuration.md, go.mod, go.sum, pkg/core/dump.go, pkg/core/dumpoptions.go, pkg/database/dump.go, pkg/database/mysql/dump.go, pkg/database/mysql/table.go, pkg/database/mysql/view.go, test/backup_test.go
=> support for dumping triggers and functions and procedures

cmd/dump.go, cmd/restore.go, docs/configuration.md, pkg/compression/bzip2.go, pkg/compression/compressor.go, pkg/compression/gzip.go, pkg/compression/none.go
=> add support for no compression

.github/workflows/ci.yaml, Makefile, test/backup_log_containers.go, test/backup_nolog_containers.go, test/backup_teardown_test.go, test/backup_test.go, test/package_noteardown_test.go, test/util_test.go
* remove accidental extra call of `make test` in the CI file
* simplify integration test to use env var rather than build tags, just makes it easier for IDEs to use, to see, etc.
=> Simplify integration tests

pkg/core/dump.go, pkg/core/timer.go
Adds two messages.
First, when a dump is complete, report an info message that dump is complete. We already have an info message for dump started, so this complements it. Debug messages already add a lot more.
Second, when a timed run is complete, log how long until the next run, also as an info message. This required a bit more work, as the timer channel needs to carry that info, but it was a simple change.
=> Info message complete
